version: "3"
services:
    web:
        build:
            context: .
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py wait_for_db && python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./:/code
        env_file:
            - .env

    redis:
      image: "redis:alpine"

    celery:
      build:
        context: .
        dockerfile: Dockerfile
      command: >
        sh -c "export DJANGO_SETTINGS_MODULE=app.settings &&
        celery -A social_media worker -l info"
      depends_on:
        - web
        - redis
      restart: on-failure
      env_file:
        - .env

    celery-beat:
      build:
        context: .
        dockerfile: Dockerfile
      command: >
        sh -c "export DJANGO_SETTINGS_MODULE=app.settings &&
        celery -A social_media_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
      depends_on:
        - web
        - redis
      restart: on-failure
      env_file:
        - .env

    flower:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5555:5555"
      command: "celery -A social_media_api flower --address=0.0.0.0"
      depends_on:
        - celery
      env_file:
        - .env
