# Generated by Django 4.2.6 on 2023-10-25 16:11

from django.db import migrations
import social_media.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", social_media.models.UserManager()),
            ],
        ),
    ]
